name: 'Africastalking SMS Action'
description: 'Send an SMS from GitHub Actions using Africastalking Programmable SMS'
author: 'Alpha Olomi'
branding:
  icon: 'message-circle'
  color: 'blue'
inputs:  
  AT_API_KEY:
    required: true
     description: 'A Africastalking API Key. Should be stored in environment'
  AT_USERNAME:
    required: true
    description: 'A Africastalking Username. Should be stored in environment'
  fromPhoneNumber:
    description: 'Sender ID'
    required: true
  toPhoneNumber:
    required: true
    description: 'The phone number to send the message to.'
outputs:
  message_status:
    description: 'The status of the message sent'
runs:
  using: 'node16'
  main: 'dist/index.js'
