name: 'Action Africastalking'
description: 'Send text messages to mobile number of choice via AfricastalkingSMS API'
author: 'Alpha Olomi'
branding:
  icon: 'code'
  color: 'blue'
inputs:  
  AT_API_KEY:
    required: true
  AT_USERNAME:
    required: true
  AT_MOBILE_NUMBER:
    required: true
outputs:
  message_status: # id of output
    description: 'The notifcation message response status.'
runs:
  using: 'node12'
  main: 'dist/index.js'
