name: 'SMS on Pr'
on:
  pull_request:

jobs:
  sms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Send SMS
        uses: alphaolomi/actions-africastalking@main
        with:
          fromPhoneNumber: 'INFO'
          toPhoneNumber: '+255747991498'
          message: 'PR ${{ github.event.pull_request.number }} has been ${{ github.event.action }}' on ${{ github.repository }} by ${{ github.actor }}'
        env:
          AT_API_KEY: ${{ secrets.AT_API_KEY }}
          AT_USERNAME: ${{ secrets.AT_USERNAME }}
